"""Add membership fees table

Revision ID: 53b90a3c5b36
Revises: 8601066666bd
Create Date: 2025-12-16 09:35:56.802117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b90a3c5b36'
down_revision = '8601066666bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=16), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('amount_per_account', sa.Float(), nullable=False),
    sa.Column('number_of_accounts', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'year', name='_member_year_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership_fee')
    # ### end Alembic commands ###
