"""Initial migration

Revision ID: 8601066666bd
Revises: 
Create Date: 2025-05-27 12:46:07.130449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8601066666bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_loan')
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_repayment_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('expected_monthly_payment', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('monthly_interest_amount', sa.Float(), nullable=False))
        batch_op.drop_column('monthly_installment_deadline')

    with op.batch_alter_table('member_history', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('history_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history_id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_installment_deadline', sa.INTEGER(), nullable=False))
        batch_op.drop_column('monthly_interest_amount')
        batch_op.drop_column('expected_monthly_payment')
        batch_op.drop_column('first_repayment_date')

    op.create_table('_alembic_tmp_loan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('repayment_period_months', sa.INTEGER(), nullable=False),
    sa.Column('monthly_interest_rate', sa.FLOAT(), nullable=False),
    sa.Column('late_interest_rate', sa.FLOAT(), nullable=False),
    sa.Column('total_repayment_amount', sa.FLOAT(), nullable=False),
    sa.Column('deadline', sa.DATE(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('first_repayment_date', sa.DATE(), nullable=False),
    sa.Column('expected_monthly_payment', sa.FLOAT(), nullable=False),
    sa.Column('monthly_interest_amount', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
