"""Add detailed loan repayment fields

Revision ID: be0ea8168d12
Revises: 53b90a3c5b36
Create Date: 2026-01-03 10:28:47.515274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0ea8168d12'
down_revision = '53b90a3c5b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_repayment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_principal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('monthly_interest', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('late_months', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('late_penalty', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_repayment', schema=None) as batch_op:
        batch_op.drop_column('late_penalty')
        batch_op.drop_column('late_months')
        batch_op.drop_column('monthly_interest')
        batch_op.drop_column('monthly_principal')

    # ### end Alembic commands ###
